# Generated by Django 5.2 on 2025-05-11 05:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(help_text='Unique identifier for the airport eg INV', max_length=10, unique=True)),
                ('airport_name', models.CharField(help_text='Name of airport', max_length=100)),
                ('airport_location', models.CharField(help_text='Location', max_length=100)),
                ('airport_timezone', models.CharField(help_text='Timezone of the airport', max_length=50)),
                ('airport_latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the airport', max_digits=9)),
                ('airport_longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the airport', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(help_text="Customer's email address", max_length=100, unique=True)),
                ('customer_first_name', models.CharField(help_text="Customer's first name", max_length=100)),
                ('customer_last_name', models.CharField(help_text="Customer's last name", max_length=100)),
                ('customer_phone', models.CharField(help_text="Customer's contact number", max_length=20)),
                ('customer_loyalty_points', models.FloatField(default=0, help_text='Frequent flyer points')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft_type', models.CharField(help_text='Type/model of the aircraft', max_length=100)),
                ('craft_capacity', models.IntegerField(help_text='Maximum passenger capacity')),
                ('craft_id', models.CharField(help_text='Registration number of the aircraft', max_length=100, unique=True)),
                ('craft_remaining_capacity', models.IntegerField(help_text='Remaining capacity of the aircraft')),
                ('craft_status', models.CharField(help_text='Status of the aircraft (e.g., Available, In Maintenance)', max_length=50)),
                ('craft_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_location', to='ass2.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('flight_departure_time', models.DateTimeField()),
                ('flight_arrival_time', models.DateTimeField()),
                ('flight_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flight_status', models.CharField(default='Scheduled', help_text='Status of the flight (e.g., Scheduled, Delayed, Cancelled)', max_length=50)),
                ('flight_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass2.aircraft')),
                ('flight_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='ass2.airport')),
                ('flight_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='ass2.airport')),
            ],
            options={
                'ordering': ['flight_departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique booking reference number', unique=True)),
                ('booking_created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when booking was made')),
                ('booking_requests', models.CharField(help_text='Special requests or notes', max_length=100)),
                ('booking_status', models.CharField(default='Pending', help_text='Status of the booking (e.g., Confirmed, Cancelled)', max_length=50)),
                ('booking_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the flight')),
                ('booking_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass2.customer')),
                ('booking_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass2.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the payment')),
                ('payment_status', models.CharField(default='Pending', help_text='Status of the payment (e.g., Completed, Failed)', max_length=50)),
                ('payment_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass2.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(help_text='Type of route prestige, shuttle etc', max_length=100)),
                ('route_frequency', models.IntegerField(help_text='Frequency of the route in days')),
                ('route_price', models.DecimalField(decimal_places=2, help_text='Price of the route', max_digits=10)),
                ('route_duration', models.DecimalField(decimal_places=2, help_text='Typical flight duration in hours', max_digits=4)),
                ('route_return_duration', models.DecimalField(blank=True, decimal_places=2, help_text='Return flight duration in hours', max_digits=4, null=True)),
                ('route_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_aircraft', to='ass2.aircraft')),
                ('route_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='ass2.airport')),
                ('route_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origins', to='ass2.airport')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='ass2.route'),
        ),
    ]
